// File: Bidi.h
//
// For use with Bidi Reference Implementation
// For rights, disclaimers and description see associated BIDI.CPP file
//
// Copyright (C) 1999-2001, ASMUS, Inc.     All Rights Reserved

#if WINDOWS_UI
	// disable some warnings generated by windows.h
	#pragma warning (disable : 4514 4201)
#endif

#if JAVA_INTERFACE
  #include "biditest.h"	// not part of the reference implementation
#else
  #if WINDOWS_UI > 1
	#include "main.h"	    // private header, includes Windows,h
	#include "window.h"     // center
	#define DEMO 1			// force demo mode
	#ifdef DEBUG_ENABLED
	  #define DEBUGGING 1	// conditionally enable debug support 
	#endif					// for private build
  #elif WINDOWS_UI
    #define ASSERT(x)       // suppress ASSERTs for standalone
    #include "windows.h"    // standard include file for windows
    #include "windowsx.h"   // extended include file for windows
  #else
	// commandline version, define printf based ASSERT
	#include <stdio.h>
    #define ASSERT(x) if (!(x)) fprintf(stdout, "assert failed: %s\n", #x); else ;
  #endif
#endif

// provides constants for UI elements declared in BIDI.RC
#ifndef IDC_INPUT
#define IDC_INPUT                       2189
#define IDC_LEVEL                       2190
#define IDC_EX_LEVEL                    2190
#define IDC_DISPL                       2191
#define IDC_TYPES                       2192
#define IDC_N_TYPES                     2193
#define IDC_IM_LEVEL                    2194
#define IDC_W_TYPES                     2195
#define IDC_RLE                         2196
#define IDC_LRE                         2197
#define IDC_RLO                         2198
#define IDC_LRO                         2199
#define IDC_MIRROR                      2200
#define IDC_RLM                         2201
#define IDC_NBSP                        2202
#define IDC_X_TYPES                     2202
#define IDC_LRM                         2204
#define IDC_CLEAN                       2205
#define IDC_LS                          2206

#define IDC_LEGEND                      2216
#define IDC_BASELEVEL                   2217
#define IDC_IMPLICIT					2203
#endif

// duplicate some windows.h defines for commandline
#ifndef TEXT
#define TCHAR  char
#define LPTSTR char *
#endif

#if WINDOWS_UI
BOOL CALLBACK BidiDlgProc(HWND hwndDlg, UINT message, WPARAM wParam, LPARAM lParam);
#endif

#ifdef _MAIN_H_
BOOL CALLBACK BidiDlgProc(HWND hwndDlg, UINT message, WPARAM wParam, LPARAM lParam);
#endif
