// File: Bidi.h
//
// For use with Bidi Reference Implementation
// For rights, disclaimers and description see associated BIDI.CPP file
//
// Copyright (C) 1999-2001, ASMUS, Inc.     All Rights Reserved

#if WINDOWS_UI
	// disable some warnings generated by windows.h
	#pragma warning (disable : 4514 4201)
#endif

#if JAVA_INTERFACE
  #include "biditest.h"	// not part of the reference implementation
#else
  #if WINDOWS_UI > 1
	#include "main.h"	    // private header, includes Windows,h
	#include "window.h"     // center
	#define DEMO 1			// force demo mode
	#ifdef DEBUG_ENABLED
	  #define DEBUGGING 1	// conditionally enable debug support 
	#endif					// for private build
  #elif WINDOWS_UI
    #define ASSERT(x)       // suppress ASSERTs for standalone
    #include "windows.h"    // standard include file for windows
    #include "windowsx.h"   // extended include file for windows
  #else
	// commandline version, define printf based ASSERT
	#include <stdio.h>
    #define ASSERT(x) if (!(x)) fprintf(stdout, "assert failed: %s\n", #x); else ;
  #endif
#endif

// provides constants for UI elements declared in BIDI.RC
#ifndef IDC_INPUT
#define IDC_INPUT                       4189
#define IDC_LEVEL                       4190
#define IDC_EX_LEVEL                    4190
#define IDC_DISPL                       4191
#define IDC_TYPES                       4192
#define IDC_N_TYPES                     4193
#define IDC_IM_LEVEL                    4194
#define IDC_W_TYPES                     4195
#define IDC_RLE                         4196
#define IDC_LRE                         4197
#define IDC_RLO                         4198
#define IDC_LRO                         4199
#define IDC_MIRROR                      4200
#define IDC_RLM                         4201
#define IDC_NBSP                        4202
#define IDC_X_TYPES                     4202
#define IDC_LRM                         4204
#define IDC_CLEAN                       4205
#define IDC_LS                          4206

#define IDC_LEGEND                      4216
#define IDC_BASELEVEL                   4217
#define IDC_IMPLICIT					4203
#endif

// duplicate some windows.h defines for commandline
#ifndef TEXT
#define TCHAR  char
#define LPTSTR char *
#endif

#if WINDOWS_UI
BOOL CALLBACK BidiDlgProc(HWND hwndDlg, UINT message, WPARAM wParam, LPARAM lParam);
#endif

#ifdef _MAIN_H_
BOOL CALLBACK BidiDlgProc(HWND hwndDlg, UINT message, WPARAM wParam, LPARAM lParam);
#endif
